# Generated by Django 3.1.4 on 2020-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banqueteria', models.CharField(max_length=50)),
                ('pack', models.CharField(max_length=50, verbose_name='Promos')),
                ('precio', models.CharField(max_length=50)),
                ('stock', models.BooleanField(default=False)),
            ],
        ),
    ]
