# Generated by Django 3.1.4 on 2020-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tipo_prod', models.CharField(max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
